# Generated by Django 3.2 on 2023-10-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_genretitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
    ]
