# Generated by Django 3.2 on 2023-10-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_title_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genre_titles', through='reviews.GenreTitle', to='reviews.Genre'),
        ),
    ]
