# Generated by Django 3.2 on 2023-10-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_title_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
