# Generated by Django 3.2 on 2023-10-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_remove_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genre',
            new_name='genres',
        ),
    ]
