# Generated by Django 3.2 on 2023-10-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_rename_genre_title_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
